name: ahlul_quran_app
description: "Aplikasi Jurnal Cerdas 1% Ahlul Qur'an"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Paket-paket yang akan kita butuhkan nanti
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2 # Untuk penyimpanan offline
  chart_sparkline: ^1.0.13   # Untuk membuat kurva
  audioplayers: ^5.2.1       # Untuk audio notifikasi

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Aset audio akan ditambahkan di sini nanti
  # assets:
  #   - assets/audio/
