name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # checkout terbaru

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # atau versi yang lo pake

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4   # ⬅️ ini diganti v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

